addons:
  ssh_known_hosts: web172.dogado.net

install:
  - curl -LO https://github.com/gohugoio/hugo/releases/download/v0.69.0/hugo_extended_0.69.0_Linux-64bit.deb
  - sudo dpkg -i hugo_extended_0.69.0_Linux-64bit.deb
  - sudo apt-get sshpass rsync

script:
  - hugo

deploy:
  - provider: script
    script: ./deploy.sh
    skip_cleanup: true
    on:
      branch: master
